import type { VideoItem } from "./types";

export const asset = "https://innovators.ventures/wp-content/uploads";

export const photo = (id: string, width = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=82`;

export const realImages = {
  healthcare: photo("photo-1576091160399-112ba8d25d1d"),
  fintech: photo("photo-1551288049-bebda4e38f71"),
  ai: photo("photo-1518770660439-4636190af475"),
  show: photo("photo-1505373877841-8d25f7d46678"),
  biotech: photo("photo-1532187863486-abf9dbad1b69"),
  energy: photo("photo-1509391366360-2e959784a276"),
  connect: photo("photo-1517048676732-d65bc937f952"),
  research: photo("photo-1581091226825-a6a2a5aee158"),
  manufacturing: photo("photo-1581092918056-0c4c3acd3789"),
  proprietary: photo("photo-1558494949-ef010cbdcc31"),
  startup: photo("photo-1556761175-b413da4baf72"),
  robotics: photo("photo-1485827404703-89b55fcc595e"),
  city: photo("photo-1497366754035-f200968a6e72"),
  community: photo("photo-1522071820081-009f0129c71c"),
};

export const editorialImages = [
  realImages.healthcare,
  realImages.fintech,
  realImages.ai,
  realImages.show,
  realImages.biotech,
  realImages.energy,
  realImages.connect,
  realImages.research,
  realImages.manufacturing,
  realImages.proprietary,
  realImages.startup,
  realImages.robotics,
  realImages.city,
  realImages.community,
  photo("photo-1573164713988-8665fc963095"),
  photo("photo-1498050108023-c5249f4df085"),
  photo("photo-1516321318423-f06f85e504b3"),
  photo("photo-1460925895917-afdab827c52f"),
  photo("photo-1563986768494-4dee2763ff3f"),
  photo("photo-1521737604893-d14cc237f11d"),
  photo("photo-1552664730-d307ca884978"),
  photo("photo-1556761175-4b46a572b786"),
  photo("photo-1553877522-43269d4ea984"),
  photo("photo-1559136555-9303baea8ebd"),
  photo("photo-1535223289827-42f1e9919769"),
  photo("photo-1518186285589-2f7649de83e0"),
  photo("photo-1550751827-4bd374c3f58b"),
  photo("photo-1517077304055-6e89abbf09b0"),
  photo("photo-1526378722484-bd91ca387e72"),
  photo("photo-1582719471384-894fbb16e074"),
  photo("photo-1542744173-8e7e53415bb0"),
  photo("photo-1551434678-e076c223a692"),
  photo("photo-1522202176988-66273c2fd55f"),
  photo("photo-1531482615713-2afd69097998"),
  photo("photo-1520607162513-77705c0f0d4a"),
  photo("photo-1519389950473-47ba0277781c"),
  photo("photo-1542744094-3a31f272c490"),
  photo("photo-1517245386807-bb43f82c33c4"),
  photo("photo-1551836022-d5d88e9218df"),
  photo("photo-1518005020951-eccb494ad742"),
];

export const iconMap = {
  news: `${asset}/2021/03/2c-2.png`,
  learn: `${asset}/2022/08/2d.png`,
  build: `${asset}/2021/03/2f-2.png`,
  fund: `${asset}/2022/08/2e.png`,
  market: `${asset}/2022/08/2b.png`,
  sales: `${asset}/2022/08/2g.png`,
  discover: `${asset}/2021/03/2a-2.png`,
  community: `${asset}/2022/08/2d.png`,
  intelligence: `${asset}/2021/03/2a-2.png`,
  demo: "play",
};

export const topModules = [
  ["News", iconMap.news],
  ["Learn", iconMap.learn],
  ["Build", iconMap.build],
  ["Funding", iconMap.fund],
  ["Marketing", iconMap.market],
  ["Sales", iconMap.sales],
  ["Discover", iconMap.discover],
  ["Community", iconMap.community],
  ["Intelligence", iconMap.intelligence],
  ["Demo", iconMap.demo],
];

export const journeyActions = [
  ["Broadcast\nMy Innovation", "https://innovators.ventures/pricing/"],
  ["My Innovation\nJourney", "https://www.innovators.ventures/innovators"],
  ["Sign in\nSign up", "https://innovators.ventures/log-in/"],
];

export const marketStats = [
  ["Innovation Index", "+2.4%", "up"],
  ["AI Deals", "+18", "up"],
  ["Climate Tech", "-0.8%", "down"],
  ["Robotics", "+1.6%", "up"],
  ["Health AI", "+3.1%", "up"],
  ["Quantum", "+0.7%", "up"],
];

export const tickerItems = [
  "Weather 72F",
  "Time 12:43 AM",
  "Stocks: Innovation Index +2.4%",
  "AI Deals +18",
  "Robotics +1.6%",
  "Health AI +3.1%",
  "Quantum +0.7%",
  "Climate Tech -0.8%",
];

export const landingStats = [
  ["11", "sectors tracked"],
  ["22", "innovation desks"],
  ["4", "leader circles"],
  ["70+", "video slots"],
];

export const landingActions = [
  {
    label: "Broadcast My Innovation",
    meta: "Launch your company, product, or ecosystem story.",
    href: "https://innovators.ventures/pricing/",
  },
  {
    label: "Explore Innovation Markets",
    meta: "Scan AI, healthcare, fintech, deeptech, robotics, and more.",
    module: "US Innovation Landscape",
  },
  {
    label: "Join My Innovation Journey",
    meta: "Save videos, follow leaders, and build a personal innovation feed.",
    href: "https://www.innovators.ventures/innovators",
  },
];

export const featureTiles = [
  "Leaders of the Month",
  "Innovators of the Month",
  "Mission",
  "AI for Sciences",
  "AI for Industries",
  "AI for P",
  "INNOverse Show",
  "Deal",
  "Product Launch",
  "Demo Day",
  "US Innovation Landscape",
  "World Innovation Landscape",
  "Q Leap",
  "Interactive Learning",
  "Tech D",
  "Super Platform",
  "For Everything Innovation",
  "For Everyone",
  "Innovation Challenge",
  "Live Streaming",
  "Innovation Meme",
  "AI co-pilot",
];

export const featureLinks: Partial<Record<(typeof featureTiles)[number], string>> = {
  "US Innovation Landscape": "/usa",
  "World Innovation Landscape": "/world",
};

export const billboard = (name: string) => `/assets/billboards/${name}.jpg`;

export const featureVisuals = [
  billboard("city-square"),
  billboard("gateway-arch"),
  billboard("innovation-campus"),
  billboard("circuit-state"),
  billboard("robotics-lab"),
  realImages.ai,
  billboard("broadcast-stage"),
  billboard("innovation-bulb"),
  billboard("robotics-lab"),
  billboard("city-river"),
  billboard("us-energy-map"),
  billboard("us-photo-map"),
  billboard("us-network-map"),
  realImages.research,
  realImages.ai,
  billboard("innovation-bulb"),
  realImages.community,
  billboard("city-waterfront"),
  billboard("gateway-arch"),
  billboard("broadcast-stage"),
  realImages.community,
  realImages.robotics,
];

export const featureCtas = [
  "Nominate",
  "Explore",
  "Read",
  "Discover",
  "Discover",
  "Discover",
  "Register",
  "View Deals",
  "Explore",
  "Apply",
  "Explore",
  "Explore",
  "Read More",
  "Start",
  "Learn",
  "Open",
  "Browse",
  "Join",
  "Participate",
  "Watch",
  "View",
  "Try Now",
];

export const categories = [
  "Healthcare",
  "Life Sciences & Biotech",
  "MedTech",
  "Fintech",
  "Digital Commerce",
  "AI",
  "Robotics",
  "Clean Tech",
  "Advanced Manufacturing",
  "Critical Minerals",
  "Agriculture",
  "Space",
  "Quantum",
  "New Materials",
  "Cybersecurity",
  "Enterprise Software",
  "DeepTech",
];

export const audiences = [
  "Universities",
  "Accelerators",
  "Corporations",
  "Startups",
  "VCs",
  "Service providers",
  "Industry Association",
  "Countries",
  "abc",
  "Grassroot communities",
  "Subscriptions",
  "Saved Videos",
];

export const audienceIcons: Record<string, string> = {
  Universities: "university",
  Accelerators: "rocket",
  Corporations: "building",
  Startups: "sprout",
  VCs: "wallet",
  "Service providers": "briefcase",
  "Industry Association": "award",
  Countries: "globe",
  abc: "letters",
  "Grassroot communities": "leaf",
  Subscriptions: "receipt",
  "Saved Videos": "video",
};

export const videos: VideoItem[] = [
  {
    title: "Digital health delivery",
    category: "Healthcare",
    audience: "Startups",
    image: editorialImages[0],
    source: "Innovators Health",
    age: "1h",
    reactions: 106,
  },
  {
    title: "Neo banks and payments",
    category: "Fintech",
    audience: "VCs",
    image: editorialImages[1],
    source: "Market Desk",
    age: "2w",
    reactions: 809,
  },
  {
    title: "AI, computing and data",
    category: "AI",
    audience: "Corporations",
    image: editorialImages[2],
    source: "AI Brief",
    age: "2w",
    reactions: 133,
  },
  {
    title: "Monthly innovation shows",
    category: "DeepTech",
    audience: "Universities",
    image: editorialImages[3],
    source: "INNOverse",
    age: "3w",
    reactions: 234,
  },
  {
    title: "BIO 2025 landscape",
    category: "Biotech",
    audience: "Industry Association",
    image: editorialImages[4],
    source: "Bio Desk",
    age: "1d",
    reactions: 521,
  },
  {
    title: "Worldwide innovation economies",
    category: "Energy",
    audience: "Countries",
    image: editorialImages[5],
    source: "World Desk",
    age: "5d",
    reactions: 127,
  },
  {
    title: "University lab spinouts",
    category: "Life Sciences & Biotech",
    audience: "Universities",
    image: editorialImages[6],
    source: "Campus Lab",
    age: "6h",
    reactions: 318,
  },
  {
    title: "MedTech workflow pilots",
    category: "MedTech",
    audience: "Service providers",
    image: editorialImages[7],
    source: "MedTech Review",
    age: "9h",
    reactions: 214,
  },
  {
    title: "Factory intelligence systems",
    category: "Advanced Manufacturing",
    audience: "Corporations",
    image: editorialImages[8],
    source: "Industry Desk",
    age: "1d",
    reactions: 442,
  },
  {
    title: "Secure proprietary data rooms",
    category: "Cybersecurity",
    audience: "Corporations",
    image: editorialImages[9],
    source: "Security Lab",
    age: "4d",
    reactions: 188,
  },
  {
    title: "Founder distribution playbook",
    category: "Enterprise Software",
    audience: "Startups",
    image: editorialImages[10],
    source: "Startup Desk",
    age: "8h",
    reactions: 367,
  },
  {
    title: "Robotics buyer challenge",
    category: "Robotics",
    audience: "Industry Association",
    image: editorialImages[11],
    source: "Robotics Lab",
    age: "2d",
    reactions: 291,
  },
  {
    title: "City innovation incentives",
    category: "Clean Tech",
    audience: "Countries",
    image: editorialImages[12],
    source: "City Desk",
    age: "1w",
    reactions: 175,
  },
  {
    title: "Community builder channels",
    category: "Digital Commerce",
    audience: "Grassroot communities",
    image: editorialImages[13],
    source: "Community Desk",
    age: "3d",
    reactions: 249,
  },
  {
    title: "AI product copilots",
    category: "AI",
    audience: "Service providers",
    image: editorialImages[14],
    source: "Product Lab",
    age: "5h",
    reactions: 514,
  },
  {
    title: "Developer platform launches",
    category: "Enterprise Software",
    audience: "Startups",
    image: editorialImages[15],
    source: "Platform Desk",
    age: "11h",
    reactions: 226,
  },
  {
    title: "Interactive learning demos",
    category: "AI",
    audience: "Universities",
    image: editorialImages[16],
    source: "Learning Lab",
    age: "2d",
    reactions: 394,
  },
  {
    title: "Venture capital signals",
    category: "Fintech",
    audience: "VCs",
    image: editorialImages[17],
    source: "Capital Desk",
    age: "7h",
    reactions: 617,
  },
  {
    title: "Clean energy storage pilots",
    category: "Clean Tech",
    audience: "Corporations",
    image: editorialImages[18],
    source: "Energy Desk",
    age: "1d",
    reactions: 338,
  },
  {
    title: "Corporate innovation pods",
    category: "Advanced Manufacturing",
    audience: "Corporations",
    image: editorialImages[19],
    source: "Enterprise Desk",
    age: "12h",
    reactions: 277,
  },
  {
    title: "Service provider demo kits",
    category: "Digital Commerce",
    audience: "Service providers",
    image: editorialImages[20],
    source: "Service Desk",
    age: "4h",
    reactions: 203,
  },
  {
    title: "Open ecosystem partnerships",
    category: "Agriculture",
    audience: "Industry Association",
    image: editorialImages[21],
    source: "Ecosystem Desk",
    age: "1w",
    reactions: 461,
  },
  {
    title: "Innovation operating dashboards",
    category: "Enterprise Software",
    audience: "Accelerators",
    image: editorialImages[22],
    source: "Ops Desk",
    age: "2d",
    reactions: 306,
  },
  {
    title: "Growth market briefings",
    category: "Digital Commerce",
    audience: "Accelerators",
    image: editorialImages[23],
    source: "Market Brief",
    age: "3d",
    reactions: 352,
  },
  {
    title: "Immersive prototype rooms",
    category: "DeepTech",
    audience: "Universities",
    image: editorialImages[24],
    source: "Prototype Lab",
    age: "1d",
    reactions: 287,
  },
  {
    title: "Data infrastructure upgrades",
    category: "Critical Minerals",
    audience: "Corporations",
    image: editorialImages[25],
    source: "Infrastructure Desk",
    age: "6d",
    reactions: 198,
  },
  {
    title: "Cyber trust frameworks",
    category: "Cybersecurity",
    audience: "Countries",
    image: editorialImages[26],
    source: "Trust Desk",
    age: "5d",
    reactions: 321,
  },
  {
    title: "Engineering launch stacks",
    category: "Enterprise Software",
    audience: "Startups",
    image: editorialImages[27],
    source: "Build Desk",
    age: "16h",
    reactions: 268,
  },
  {
    title: "Digital adoption playbooks",
    category: "MedTech",
    audience: "Service providers",
    image: editorialImages[28],
    source: "Adoption Desk",
    age: "2d",
    reactions: 403,
  },
  {
    title: "Bio discovery pipelines",
    category: "Life Sciences & Biotech",
    audience: "Universities",
    image: editorialImages[29],
    source: "Discovery Desk",
    age: "13h",
    reactions: 375,
  },
  {
    title: "Boardroom innovation agenda",
    category: "AI",
    audience: "Corporations",
    image: editorialImages[30],
    source: "Board Brief",
    age: "1d",
    reactions: 444,
  },
  {
    title: "Health system partnerships",
    category: "Healthcare",
    audience: "Service providers",
    image: editorialImages[31],
    source: "Health Systems",
    age: "2d",
    reactions: 512,
  },
  {
    title: "Remote innovation teams",
    category: "Space",
    audience: "Startups",
    image: editorialImages[32],
    source: "Team Desk",
    age: "9h",
    reactions: 238,
  },
  {
    title: "Demo day storytelling",
    category: "DeepTech",
    audience: "Accelerators",
    image: editorialImages[33],
    source: "Demo Desk",
    age: "1w",
    reactions: 579,
  },
  {
    title: "Regional ecosystem maps",
    category: "New Materials",
    audience: "Countries",
    image: editorialImages[34],
    source: "Map Desk",
    age: "4d",
    reactions: 255,
  },
  {
    title: "Investor research rooms",
    category: "Quantum",
    audience: "VCs",
    image: editorialImages[35],
    source: "Investor Desk",
    age: "3d",
    reactions: 349,
  },
  {
    title: "Launch meeting intelligence",
    category: "Enterprise Software",
    audience: "Service providers",
    image: editorialImages[36],
    source: "Launch Desk",
    age: "8h",
    reactions: 286,
  },
  {
    title: "Founder learning studio",
    category: "Interactive Learning",
    audience: "Grassroot communities",
    image: editorialImages[37],
    source: "Learning Studio",
    age: "2w",
    reactions: 199,
  },
  {
    title: "Product-market interviews",
    category: "Digital Commerce",
    audience: "Startups",
    image: editorialImages[38],
    source: "PMF Desk",
    age: "2d",
    reactions: 433,
  },
  {
    title: "Architecture for innovation hubs",
    category: "Advanced Manufacturing",
    audience: "Countries",
    image: editorialImages[39],
    source: "Hub Desk",
    age: "6d",
    reactions: 309,
  },
];

export const leaderGroups = {
  Academia: [
    ["Robert Langer", `${asset}/2022/04/Robert_Langer_BioTech_Awards_Video_laboratory-e1650812997315.png`],
    ["Jeremy Weinstein", `${asset}/2026/06/100324_Jeremy_Weinstein_159-e1781027980977.webp`],
    ["Fiona Murray", `${asset}/2022/02/profile-image-41035-e1650811639655.jpeg`],
    ["Soumitra Dutta", `${asset}/2022/05/hueZBORZ_400x400-e1653102732198.jpg`],
  ],
  Industry: [
    ["Barbara Humpton", `${asset}/2025/01/Barbara-Humpton-Headshot.png`],
    ["Chris Coburn", `${asset}/2021/02/Coburn-Chris-scaled-e1615840187511.jpg`],
    ["John Kalamka", `${asset}/2023/03/mayo-e1678204925459.jpg`],
    ["Cindy Bo", `${asset}/2024/12/Cindy-Bo_v2_2x3-1.jpg`],
  ],
  Government: [
    ["Hans Vestberg", `${asset}/2024/03/hans_bio_photo_300x375.jpg`],
    ["Kevin Mahoney", `${asset}/2025/09/KevinMahoney_Expert.jpg`],
    ["David Rhew", `${asset}/2025/09/David-in-MSFT-Garden.7333-1024x683-1-e1758849575801.jpg`],
    ["Thomas Saueressig", `${asset}/2025/02/thomas-saueressig_3840x2160.webp`],
  ],
  VC: [
    ["Scott Sandell", `${asset}/2024/03/scott-sandell_landscape-e1710696409606.webp`],
    ["Nigel Morris", `${asset}/2021/06/2019-Nigel-headshot-e1623799623770.jpg`],
    ["Michael Greeley", `${asset}/2022/08/Greeley_220x220_3-e1661219172983.jpg`],
    ["Matt Kozlov", `${asset}/2022/08/1110x740-md-starburst-matt-kozlov-e1661219143691.jpg`],
  ],
  Startups: [
    ["Digital Health", `${asset}/2021/03/1-2.png`],
    ["Beam Dental", `${asset}/2022/05/Copy-of-Copy-of-Black-and-Yellow-Playful-TechIT-Trifold-Brochure-8.png`],
    ["AI Compute", `${asset}/2022/03/Copy-of-Copy-of-Black-and-Yellow-Playful-TechIT-Trifold-Brochure-6.png`],
  ],
  Communities: [
    ["Health Network", `${asset}/2025/06/Video-covers-HOME-PAGE-4.jpg`],
    ["Local Builders", `${asset}/2025/07/Video-covers-HOME-PAGE-8.jpg`],
    ["Innovation Circle", `${asset}/2025/07/Video-covers-HOME-PAGE-6.jpg`],
  ],
};

export const initialIdeas = [
  "Open founder office hours for health AI pilots",
  "Invite university labs to post prototypes",
  "Create a weekly robotics buyer challenge",
  "Map local innovation incentives by region",
  "Launch a demo day for service providers",
  "Curate saved videos by sector",
];

export const news = [
  "Fintech founders are shifting from launch content to proof-led customer stories.",
  "AI co-pilots are moving into every panel: learning, sales, and post-demo follow-up.",
  "Healthcare builders are asking for stronger provider distribution playbooks.",
  "Innovation landscapes are becoming a recurring category for ecosystem partners.",
];

export const softVisuals = [
  editorialImages[6],
  editorialImages[7],
  editorialImages[8],
  editorialImages[9],
  editorialImages[24],
  editorialImages[29],
];

export const aiRows = [
  {
    label: "AI for Sciences",
    note: "Connect",
    hero: "institutions interoperability",
    cards: [
      ["Accelerate discovery", videos[14]],
      ["close the experimental loop,", videos[17]],
      ["research data.", videos[29]],
      ["Proprietary", softVisuals[3]],
    ],
  },
  {
    label: "AI for Industries",
    note: "Deploy",
    cards: [
      ["applying AI to transform how companies operate, produce, and innovate.", videos[19]],
      ["predictive maintenance, supply chain optimization, process automation,", videos[8]],
      ["quality control, digital twins of factories, AI engineering design", videos[28]],
      ["Trade secrets, operational data", softVisuals[4]],
    ],
    wide: videos[8],
  },
  {
    label: "AI for P",
    note: "Harness",
    hero: "Discovery",
    cards: [
      ["Democratize AI's benefits to individuals and communities.", videos[13]],
      ["personalized health, education, financial access, civic tools,", videos[31]],
      ["civic tools, workforce reskilling", videos[37]],
      ["workforce reskilling, local", softVisuals[5]],
    ],
  },
];

export const shorts = [
  ["AI institutions", editorialImages[6]],
  ["Signal scan", editorialImages[22]],
  ["Interoperability", editorialImages[15]],
  ["Research loop", editorialImages[29]],
  ["Open innovation", editorialImages[21]],
  ["Market memo", editorialImages[17]],
  ["Founder clip", editorialImages[32]],
  ["Co-pilot prompt", editorialImages[14]],
  ["Prototype room", editorialImages[24]],
  ["Trust systems", editorialImages[26]],
];

export const innovationColumns = [
  {
    title: "LEARN RESEARCH",
    videos: [videos[6], videos[16], videos[29], videos[33], videos[37]],
  },
  {
    title: "BUILD/ PRODUCTIVITY",
    videos: [videos[15], videos[22], videos[27], videos[36], videos[8], videos[20]],
  },
  {
    title: "MY COMMUNITY",
    videos: [videos[13], videos[21], videos[32], videos[37], videos[38]],
  },
  {
    title: "FUNDRAISING",
    videos: [videos[17], videos[23], videos[35], videos[10], videos[18]],
  },
  {
    title: "MY FAVORITE",
    videos: [videos[4], videos[24], videos[31], videos[14], videos[11]],
  },
];

export const journeyIcon = (name: string) => `/assets/journey-icons/${name}.svg`;

export const journeyNavItems = [
  { label: "LEARN", icon: journeyIcon("learn") },
  { label: "RESEARCH", icon: journeyIcon("research") },
  { label: "Build", icon: journeyIcon("build") },
  { label: "Productivity", icon: journeyIcon("productivity") },
  { label: "Fundraising", icon: journeyIcon("fundraising") },
  { label: "Marketing", icon: journeyIcon("marketing") },
  { label: "Sales", icon: journeyIcon("sales") },
  { label: "My Community", icon: journeyIcon("my_community") },
  { label: "My Favorite", icon: journeyIcon("data_intelligence") },
  { label: "My Cart", icon: journeyIcon("my_cart") },
  { label: "Intelligence", icon: journeyIcon("data_intelligence") },
];
